### ISSUE TITLE
Hash Values for Zimmerman Tool Collection Missing

### ISSUE THREAD

**Issue by rawsGit** [EricZimmerman/ericzimmerman.github.io#15]
Where can I locate the hash values of the full suite of tools, including the GetZimmermanTools.ps1 script?

**Comment by EricZimmerman** [comment]
You can generate them I guess. 

What for? Everything is signed sha256.  If the signature is intact it's all good.

**Comment by rawsGit** [comment]
To ensure data integrity, after download. I will look into how to verify sha256 digital signatures. Ok to close issue. Thanks for the prompt response.

**Comment by EricZimmerman** [comment]
The signature does that for you. If any bit changes the signature won't validate.

**Comment by rawsGit** [comment]
Understood. I also see, now, that Github also ensures commits are legitimate(https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits).
Thank you, EZ.
